version: '3'

services: 
    db:
        image: postgres:13
        env_file: .env
        
    web:
        build: .
        env_file: .env
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - .:/code
        ports:
            - "8000:8000"
        depends_on: 
            - db